
params:
  epochs : 3
  batch_size : 32
  num_classes : 10
  loss_function : sparse_categorical_crossentropy
  metrics : accuracy
  optimizer : SGD
  validation_datasize : 5000
  dataset : fashion_mnist
  input_size : 28,28,1

artifacts:
  artifacts_dir : artifacts
  model_dir : models
  plot_dir : plots
  model_name : fashion_mnist.h5

logs:
  log_dir : logs
  general_logs : general_logs
  