
params:
  epochs : 10
  batch_size : 32
  num_classes : 10
  loss_function : sparse_categorical_crossentropy
  metrics : accuracy
  optimizer : SGD
  validation_datasize : 5000
  dataset : cifar10
  input_size : 32,32,3
  patience : 5
  restore_best_weights : True

artifacts:
  artifacts_dir : artifacts
  model_dir : models
  plot_dir : plots
  model_name : cifar10.h5
  checkpoint_dir : checkpoints

logs:
  log_dir : logs
  general_logs : general_logs
  tensorboard_logs : tensorboard_logs